# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 118670b3776c1a0b7202d1b57176969d1ba89a9336ea50cda324a8cfce096652b375723ac5088065b0aa705c98e06a42da288fba9d1da618f4bcf1b6568e7b80

test:
  secret_key_base: fd19a949e64f104b28f8c2f462eb8e2497c75d743d360268878f428b16a7ba1880274355ac6c5c0dd23e7fbb22ebc5a9b80b3529888a109639c948219a23adc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

S3_BUCKET_NAME: karch-myrecipes-bucket  
AWS_ACCESS_KEY_ID: AKIAIPRU7EOADJOLN36Q
AWS_SECRET_ACCESS_KEY: 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
